name: Upload DEB artifacts to GitHub Release

on:
  workflow_run:
    workflows: ["Build Debian Packages"]
    types:
      - completed

jobs:
  upload-deb:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all DEB artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./deb-artifacts

      - name: Create / Upload assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./deb-artifacts/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
